#
# ---- ServerChangelogs by codingcat2468 ----
# Translation files can be found in the "lang" directory.
# The language shown to the player is automatically determined by
# paper/adventure based on the selected language of the client.
#

# The changelog storage is used to store all server changelogs.
# Currently, the only option available is "yaml", which stores changelogs
# in a human-readable YAML configuration file.
changelog_storage: yaml

# The format used to display the date/time of a given changelog.
# yyyy = year (with 4 digits)
# dd = day of the month (2 digits)
# MM = month of year (2 digits)
# HH = the hour (24-hour format; 2 digits)
# hh = the hour (12-hour format; 2 digits)
# mm = the minute (2 digits)
# ss = the second (2 digits)
date_format: "yyyy/dd/MM"

# The timezone in which the time a changelog was published at will be displayed.
# This can be a text identifier, such as "Europe/Paris" or a UTC offset specifier like "UTC+1".
date_timezone: "UTC"

# Whether the plugin should register a dedicated /changelog command (not /changelogS).
# This can be useful if you want a more intuitive experience for players,
# where they don't have to type "/changelogs view".
# NOTE: Changing this setting requires a restart of your server!
register_dedicated_command: true

# Whether to add a header section to the changelog dialog that will show
# above the actual changelogs. This can be used to give players a bit of context,
# or link to e.g. a discord to give feedback, follow announcements, etc.
# The actual content of this header can be changed in the language files!
dialog_header: true

# The item that will be shown next to the header of the dialog.
# This can be set to null or entirely removed to not show any item there.
# Items can be specified in the same format as the /give command,
# including additional components (e.g. custom textures)!
# Example: "minecraft:paper[minecraft:item_model='my_resourcepack:newspaper_item']"
dialog_header_item: "minecraft:written_book"