group = com.codingcat
version = 1.2.1
description = Keep players up to date on server changes using intuitive, dialog-based UIs!
url = https://modrinth.com/plugin/server-changelogs
# Comma separated list of authors
authors = codingcat2468
# Comma separated list of contributors
contributors = codingcat2468,GuavaDealer
minecraft_version = 26.1.2
minecraft_version_compat = 26.1
org.gradle.caching = true
org.gradle.configuration-cache = true
org.gradle.configureondemand = true
org.gradle.parallel = true
org.gradle.daemon = true
org.gradle.vfs.watch = false
org.gradle.jvmargs = -Xmx2g -XX:+UseParallelGC --enable-native-access=ALL-UNNAMED
kotlin.incremental = true
kotlin.caching.enabled = true
